### ISSUE TITLE
Complete community standards checklist

### ISSUE THREAD

**Issue by DerekRoberts** [bcgov/greenfield-template#114]
https://github.com/bcgov/greenfield-template/community

Checklist

- [x] Description
- [x] README
- [ ] Code of conduct
- [x] Contributing
- [x] License
- [x] Issue templates
- [x] Pull request template
- [ ] Repository admins accept content reports
